# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_steam_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steam', to='django_steam_api.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
